In [2]:
#  chi- square tst
import numpy as np
import pandas as pd 
import seaborn as sns

In [3]:
df= sns.load_dataset("tips")

In [4]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
# chi square test>> through two ways

In [6]:
df[["sex","smoker"]]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [7]:
data_table=pd.crosstab(df['sex'],df["smoker"])

In [8]:
data_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [9]:
# observed value and expected value

observed_value = data_table.values

In [12]:
# 1st approach >> allowing chi2 itself some expected values
from scipy import stats

stats_test,p,dof,expected_value =stats.chi2_contingency(observed_value)

In [13]:
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [14]:
# (observed - expected)square / expected  = chi

In [15]:
for i in zip(observed_value,expected_value):
    print(i)

(array([60, 97]), array([59.84016393, 97.15983607]))
(array([33, 54]), array([33.15983607, 53.84016393]))


In [16]:
chisquare_test = sum([(o-e)**2 / e for o,e in zip(observed_value,expected_value)])

In [17]:
chisquare_stats = chisquare_test[0]+chisquare_test[1]

In [18]:
chisquare_stats

0.001934818536627623

In [19]:
dof

1

In [20]:
alpha = 0.05

In [21]:
alpha

0.05

In [22]:
chi2_critical=stats.chi2.ppf(1-alpha,df=dof)

In [23]:
if chisquare_stats> chi2_critical:
    print("Reject the null hypothesis,  there is a relation between two categorical values")
else:
    print("Failed to reject the null hypothesis,there is no relation betweenn two categorical values")

Failed to reject the null hypothesis,there is no relation betweenn two categorical values


In [24]:
pvalue = 1-stats.chi2.cdf(x= chisquare_stats,df= dof)

In [25]:
if pvalue< alpha:
    print("Reject the null hypothesis,  there is a relation between two categorical values")
else:
    print("Failed to reject the null hypothesis,there is no relation betweenn two categorical values")

Failed to reject the null hypothesis,there is no relation betweenn two categorical values


In [26]:
# another approach to find chi2 << Direct approach
# no of hours studies daily on a weekly basis
# monday,tuesday.....sunday

expected_data = [8,5,6,8,5,7,6]
observed_data = [7,4,7,9,4,8,6]


In [27]:
sum(expected_data),sum(observed_data)

(45, 45)

In [28]:
ch_square,pvalue= stats.chisquare(observed_data,expected_data)

In [39]:
ch_square

0.9595238095238094

In [29]:
# find the critical

alpha

0.05

In [40]:
dof= len(observed_data)-1

In [41]:
dof

6

In [42]:
ch_critical = stats.chi2.ppf(1-alpha ,df=dof)

In [43]:
ch_critical

12.591587243743977

In [44]:
if ch_critical <= ch_square:
    print("reject the null h0")
else:
    print("failed to reject the h0")

failed to reject the h0


In [45]:
if pvalue< alpha:
    print("reject the null hypothesis")
else:
    print("failed to reject the null hypothesis")

failed to reject the null hypothesis


In [47]:
# Ftest

worker1 = [18,7,5,45,9,5]
worker2 = [18,4,7,8,78,5]

fstat = np.var(worker1)/np.var(worker2)
fstat

0.2904452987345827

In [48]:
df1 = len(worker1)-1
df2 = len(worker2)-1

alpha = 0.05

In [49]:
df1

5

In [50]:
df2

5

In [51]:
import scipy.stats as stats

In [54]:
critical_value =stats.f.ppf(1-alpha,dfn=df1,dfd=df2)

In [55]:
if fstat>=critical_value:
    print("Reject the null hypothesis")
else:
    print("Failed to reject the null hypothesis")

Failed to reject the null hypothesis


In [56]:
# ANOVA TEST (analysis of variance)

In [ ]:
# to compare two or more means